
//////////////////////////////////////////////////////////////////////////////
// teams and colors
//////////////////////////////////////////////////////////////////////////////

const teamNameToColorsMap = {
  Baylor: [ "green", "green", "gold", "gold", "green", "green", "gold", "gold", "green", "green"],
  BVNW: [ "purple", "purple", "white", "white", "purple",
          "purple", "black", "black", "purple", "purple" ],
  Chiefs: [ "red", "red", "yellow", "yellow", "red", "red", "yellow", "yellow", "red", "red"],
  Grinch: [ "grinchGreen", "grinchGreen", "grinchGreen", "grinchGreen", "grinchGreen",
            "grinchGreen", "grinchGreen", "grinchGreen", "grinchGreen", "grinchGreen" ],
  Halloween: [ "orange", "orange", "black", "black", "orange",
               "orange", "black", "black", "orange", "orange"],
  Iowa: ["gold", "gold", "black", "black", "gold", "gold", "black", "black", "gold", "gold"],   
  "Iowa State": ["red", "red", "gold", "gold","red", "red", "gold", "gold","red", "red"],
  "Kansas State": [ "royalPurple", "royalPurple", "black", "black", "royalPurple",
                    "royalPurple", "black", "black", "royalPurple", "royalPurple" ],
  "Kansas": [ "blue", "blue", "red", "red", "blue", "blue", "red", "red", "blue", "blue" ],
  Mavericks: [ "orange", "orange", "orange", "orange", "lightBlue",
              "lightBlue", "orange", "orange", "orange", "orange"],
  MNU: [ "blue", "blue", "blue", "blue", "fuchsia",
              "fuchsia", "blue", "blue", "blue", "blue",],
  Missouri: [ "gold", "gold", "black", "black", "gold",
              "gold", "black", "black", "gold", "gold"],
  Nebraska: [ "red", "red", "red", "red", "red", "red", "red", "red", "red", "red" ],
  Neptunes: [ "darkBlue", "darkBlue", "white", "white", "darkBlue",
              "darkBlue", "white", "white", "darkBlue", "darkBlue" ],
  "Olathe South": [ "blue", "gold", "gold", "gold", "blue",
              "blue", "gold", "gold", "gold", "blue"],
  Oklahoma: [ "crimson", "crimson", "cream", "cream", "crimson",
              "crimson", "cream", "cream", "crimson", "crimson" ],
  "Oklahoma State": [ "orange", "orange", "black", "black", "orange",
                      "orange", "black", "black", "orange", "orange" ],
  "Pittsburg State": [ "crimson", "crimson", "gold", "gold", "crimson",
              "crimson", "gold", "gold", "crimson", "crimson"],
  Rainbow: [ "darkRed", "red", "orangeRed", "orange", "yellow",
             "chartreuse", "green", "blue", "indigo", "violet"],
  Reindeer: [ "darkBrown", "darkBrown", "darkBrown", "darkBrown", "darkBrown",
              "darkBrown", "darkBrown", "darkBrown", "red", "black"],
  Rockhurst: [ "royalBlue", "royalBlue", "white", "white", "royalBlue",
               "royalBlue", "white", "white", "royalBlue", "royalBlue"],
  Roos: [ "blue", "blue", "gold", "gold", "blue", "blue", "gold", "gold", "blue", "blue"],
  Royals: [ "blue", "blue", "white", "white", "blue", "blue", "white", "white", "blue", "blue"],
  Rudolph: [ "darkBrown", "darkBrown", "darkBrown", "darkBrown", "darkBrown",
             "darkBrown", "darkBrown", "darkBrown", "red", "black"],
  Santa: [ "red", "white", "red", "white", "red", "white", "red", "white", "red", "white"],
  Snow: [ "snow", "snow", "snow", "snow", "snow", "snow", "snow", "snow", "snow", "snow"],
  "Sporting KC": [ "darkIndigo", "darkIndigo", "sportingBlue", "sportingBlue", "darkIndigo", 
              "darkIndigo", "sportingBlue", "sportingBlue", "darkIndigo", "darkIndigo"],
  "STA Saints": [ "blue", "blue", "gold","gold", "blue", "blue", "gold","gold","blue", "blue" ],
  "Texas Christian": [ "hornedFrogPurple", "hornedFrogPurple", "white", "white", "hornedFrogPurple",
                       "hornedFrogPurple", "white", "white", "hornedFrogPurple", "hornedFrogPurple" ],
  Texas: [ "orange", "orange", "white", "white", "orange",
           "orange", "white", "white", "orange", "orange"],
  "Texas Tech": [ "scarlet", "scarlet", "black", "black", "scarlet",
                  "scarlet", "black", "black", "scarlet", "scarlet" ],
  USA: [ "red", "red", "red", "red", "white", "white", "blue", "blue", "blue", "blue" ],
};

module.exports = { teamNameToColorsMap };
